baseurl = "https://bigleaf.io"
DefaultContentLanguage = "en"
title = "Bigleaf Labs"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-96610445-1"

[Params]
#  homeTitle = "Bigleaf Labs" # Set a different text for the header on the home page
  subtitle = "Big Data, Machine Learning, SDR, Security, Hacking, Life"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  customCSS = ["/css/custom.css"]
  customJS = ["js/custom.js"]

[Author]
  name = "Jason Graham"
  website = "bigleaf.io"
  email = "jgraham20@gmail.com"
  facebook = "jasonsgraham"
  googleplus = "+jgraham20" # or xxxxxxxxxxxxxxxxxxxxx
  github = "bigleafio"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "jasonsgraham"
  #reddit = "username"
  linkedin = "jason-graham-31881034"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
